/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code_java;

import code_test.Database_Connect;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author top1z
 */
public class FORM_DEMO extends javax.swing.JFrame {

    /**
     * Creates new form FORM_DEMO
     */
    Connection cn;
    Statement stm;
    DefaultComboBoxModel<String> modelcbo = new DefaultComboBoxModel();
    DefaultTableModel model = new DefaultTableModel();
    int index;
    PreparedStatement pred;
    private Date sqldate;

    public FORM_DEMO() {
        initComponents();
        try {
            cn = Database_Connect.Database("java3_bai5");

        } catch (Exception e) {
            e.printStackTrace();
        }
        modelcbo = (DefaultComboBoxModel<String>) combokhoa.getModel();
        loadcombo();
        txttenkhoa.disable();
        txtdiadiemkhoa.disable();
        model = (DefaultTableModel) tblgiaovien.getModel();

    }

    private void loadcombo() {
        try {
            String sql = "select MAKHOA from KHOA";
            stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                modelcbo.addElement(rs.getString(1));
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void mess(String s) {
        JOptionPane.showMessageDialog(this, s);
    }

    private boolean check_tt() {
        if (txtmagv.getText().equals("")) {
            mess("không được để trống");
            return true;
        } else if (txthoten.getText().equals("")) {
            mess("không được để trống");
            return true;

        } else if (txtngaysinh.getText().equals("")) {
            mess("không được để trống");
            return true;
        }

        return false;
    }
    private boolean  FK_for(){
        try {
            String sql = "select * from GIANGVIEN";
            stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                if (txtmagv.getText().equalsIgnoreCase(rs.getString("MAGIANGVIEN"))) {
                    mess("trùng mã khóa chính");
                    return true;
                }
            }
            stm.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    private void loadtable() {
        try {
            model.setRowCount(0);
            String sql = "SELECT GIANGVIEN.MAGIANGVIEN, TENGIANGVIEN , NGAYSINH,GIOITINH,\n"
                    + "KHOA.MAKHOA, TENKHOA,DIADIEM FROM KHOA"
                    + " JOIN GIANGVIEN ON KHOA.MAKHOA=GIANGVIEN.MAKHOA\n"
                    + "where KHOA.MAKHOA = ? ";
            pred = cn.prepareStatement(sql);
            pred.setString(1, combokhoa.getSelectedItem() + "");
            ResultSet rs = pred.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});

            }
            pred.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            mess("lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        combokhoa = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttenkhoa = new javax.swing.JTextField();
        txtdiadiemkhoa = new javax.swing.JTextField();
        magv = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();
        txtmagv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgiaovien = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        combokhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combokhoaItemStateChanged(evt);
            }
        });

        jLabel1.setText("mã khoa");

        jLabel2.setText("tên khoa");

        txttenkhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenkhoaActionPerformed(evt);
            }
        });

        magv.setText("magv");

        hoten.setText("hoten");

        jLabel5.setText("ngaysinh");

        jLabel6.setText("gioi tinh");

        buttonGroup1.add(rdonam);
        rdonam.setSelected(true);
        rdonam.setText("Nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("Nữ");

        tblgiaovien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "magv", "hoten", "ngay sinh", "gioi tinh", "makhoa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgiaovien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgiaovienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgiaovien);

        btnthem.setText("thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnupdate.setText("sửa");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton3.setText("xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(combokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(txttenkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtdiadiemkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(hoten)
                                        .addGap(18, 18, 18)
                                        .addComponent(txthoten))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(magv)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmagv, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdonam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdonu))
                                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txttenkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiadiemkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magv)
                    .addComponent(txtmagv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoten)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(rdonam)
                    .addComponent(rdonu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(33, 33, 33)
                        .addComponent(btnupdate)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3)
                        .addGap(35, 35, 35)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttenkhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenkhoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenkhoaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            cn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void combokhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combokhoaItemStateChanged
        // TODO add your handling code here:
        try {
            model.setRowCount(0);
            String sql = "SELECT GIANGVIEN.MAGIANGVIEN, TENGIANGVIEN , NGAYSINH,GIOITINH,\n"
                    + "KHOA.MAKHOA, TENKHOA,DIADIEM FROM KHOA JOIN GIANGVIEN ON KHOA.MAKHOA=GIANGVIEN.MAKHOA\n"
                    + "where KHOA.MAKHOA = ? ";
            pred = cn.prepareStatement(sql);
            pred.setString(1, combokhoa.getSelectedItem() + ""); 
           
            ResultSet rs = pred.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)});
                txttenkhoa.setText(rs.getString(6));
                txtdiadiemkhoa.setText(rs.getString(7));
                System.out.println(model);
            }
            pred.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            mess("lỗi");
        }
    }//GEN-LAST:event_combokhoaItemStateChanged

    private void clear() {
        txttenkhoa.setText("");
        txtdiadiemkhoa.setText("");
        txtmagv.setText("");
        txthoten.setText("");
        txtngaysinh.setText("");
//                String gt = jRadioButton1.isSelected() ? "Nam" : "Nữ";
        rdonu.setSelected(true);
        index = -1;

    }
    private void tblgiaovienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgiaovienMouseClicked
        try {
            index = tblgiaovien.getSelectedRow();
//            model.setRowCount(0);
            String sql = "SELECT GIANGVIEN.MAGIANGVIEN, TENGIANGVIEN , NGAYSINH,GIOITINH,\n"
                    + "KHOA.MAKHOA, TENKHOA,DIADIEM FROM KHOA JOIN GIANGVIEN"
                    + " ON KHOA.MAKHOA=GIANGVIEN.MAKHOA\n";
            pred = cn.prepareStatement(sql);
//            pred.setString(1, combokhoa.getSelectedItem()+"");
            ResultSet rs = pred.executeQuery();
            while (rs.next()) {
//              model.addRow(new Object[]{rs.getString(1),rs.getString(2),
//              rs.getString(3),rs.getString(4),rs.getString(5)});
                txtmagv.setText(model.getValueAt(index, 0).toString());
                txthoten.setText(model.getValueAt(index, 1).toString());
                txtngaysinh.setText(model.getValueAt(index, 2).toString());
                String gt = tblgiaovien.getValueAt(index, 3).toString();
                if (gt.equals("Nam")) {
                    rdonam.setSelected(true);
                } else {
                    rdonu.setSelected(true);
                }
                 

//                txttenkhoa.setText(model.getValueAt(index, 5).toString());
//                txtdiadiemkhoa.setText(rs.getString("DIADIEM"));
            }
            pred.close();
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            mess("lỗi");
        }
    }//GEN-LAST:event_tblgiaovienMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        check_tt();
        FK_for();
        try {
//            DateFormat format = new SimpleDateFormat("yyyy-mm-dd"); 
//            java.util.Date date =  format.parse(txtngaysinh.getText());
//            SimpleDateFormat formatdate = new SimpleDateFormat("yyyy-mm-dd");
//              String ndt =  formatdate.format(date);
//            java.sql.Date slqdate = java.sql.Date.valueOf(ndt);
            String sql = "insert GIANGVIEN values (?,?,?,?,?)";
            pred = cn.prepareStatement(sql);
            pred.setString(1, txtmagv.getText());
            pred.setString(2, txthoten.getText());
            String gt = rdonam.isSelected() ? "nam" : "nữ";
            pred.setString(3, gt);

            pred.setString(4, txtngaysinh.getText());
            pred.setString(5, combokhoa.getSelectedItem() + "");
            pred.executeUpdate();
            loadtable();
            mess("đã thêm");
            clear();
            stm.close();

        } catch (Exception e) {
//            e.printStackTrace();
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            index = tblgiaovien.getSelectedRow();
            String sql = "delete from  GIANGVIEN where    MAGIANGVIEN =?";
            pred = cn.prepareStatement(sql);
            pred.setString(1, txtmagv.getText());
            int row = pred.executeUpdate();
            if (row > 0) {
                mess("đã xóa");
                clear();
                loadtable();
            } else {
                mess("bug");
            }

            pred.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try {
            index = tblgiaovien.getSelectedRow();
            String sql = "update GIANGVIEN set MAGIANGVIEN =? ,TENGIANGVIEN=? ,"
                    + " GIOITINH=? ,NGAYSINH=?  where  MAGIANGVIEN =?";
            pred = cn.prepareStatement(sql);
            pred.setString(1, txtmagv.getText());
            pred.setString(2, txthoten.getText());
            String gt = rdonam.isSelected() ? "Nam" : "Nữ";
            if (gt.equals("Nam")) {
                rdonam.setSelected(true);
            } else {
                rdonu.setSelected(true);
            }
            pred.setString( 3, gt);
            pred.setString(4, txtngaysinh.getText());
            pred.setString(5,  model.getValueAt(index, 0).toString());
            int row = pred.executeUpdate();
            if (row > 0) {
                mess("đã update");
                clear();
                loadtable();
            } else {
                mess("bug");
            }
            pred.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_DEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_DEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_DEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_DEMO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_DEMO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combokhoa;
    private javax.swing.JLabel hoten;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel magv;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTable tblgiaovien;
    private javax.swing.JTextField txtdiadiemkhoa;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmagv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txttenkhoa;
    // End of variables declaration//GEN-END:variables
}
