/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code_thi;

import code_test.Database_Connect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author top1z
 */
public class FORM2 extends javax.swing.JFrame {

    /**
     * Creates new form FORM2
     */
    Connection cn;
    Statement stm;
    PreparedStatement pred;
    int index;
    DefaultComboBoxModel<String> modelcomb = new DefaultComboBoxModel<>();
    
    public FORM2(String masv, String hoten, String idclass, String gt) {
        initComponents();
        setLocationRelativeTo(null);
        try {
            cn = Database_Connect.Database("QLSV");
        } catch (Exception e) {
            e.printStackTrace();
        }
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        modelcomb = (DefaultComboBoxModel) combomid.getModel();
        loadcombobox();
        txtmasv.setText(masv);
        txthoten.setText(hoten);
        combomid.setSelectedItem(idclass);
        gt = rbonam.isSelected() ? "nam" : "nữ";
        if (gt.equals("nam")) {
            rbonam.setSelected(true);
        } else {
            rbonu.setSelected(true);
        }
    }
    
//    private FORM2() {
//    }
//    
    private void mess(String s) {
        JOptionPane.showMessageDialog(this, s);
    }
    
    private void loadcombobox() {
        try {
            String sql = "select IDCLASS from CLASS ";
            stm = cn.createStatement();
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                modelcomb.addElement(rs.getString("IDCLASS"));
            }
            stm.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void check_dl() {
        if (txtmasv.getText().equals("")) {
            mess("masv khong để trống");
            return;
        } else if (txtmasv.getText().equals("")) {
            mess("hoten khong để trống");
            return;
        }
    }
     private boolean check_khoa(){
        try{
        String sql = "select   STUDENT.Masv from STUDENT";
            stm = cn.createStatement();
            ResultSet rs= stm.executeQuery(sql);
            while (rs.next()) {                
                if (txtmasv.getText().equalsIgnoreCase(rs.getString("Masv"))) {
                    mess("bug khoá");
                    return true;
                }
                
            }
            stm.close();
           
        } catch (Exception e) {
            e.printStackTrace();
        }
         return false;
    }
    
    private void xoa() {
        int chonce = JOptionPane.showConfirmDialog(this, "xóa?");
        if (chonce == -1) {
            mess("chưa chọn dòng");
            return;
        } else {
            try {
                String sql = "delete from STUDENT where MaSV =? ";
                pred = cn.prepareStatement(sql);
                pred.setString(1, txtmasv.getText());
                pred.executeUpdate();
                mess("đã xóa");
                clear();
                FORM1 f = new FORM1();
                f.loaddata();
                pred.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }

    private void clear() {
        txtmasv.setText("");
        txthoten.setText("");
        combomid.setSelectedItem("");
        rbonam.setSelected(true);
        index = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtmasv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        rbonam = new javax.swing.JRadioButton();
        rbonu = new javax.swing.JRadioButton();
        combomid = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("masv");

        jLabel2.setText("họ tên");

        jLabel3.setText("id class");

        jLabel4.setText("giới tính");

        btnreset.setText("reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnthem.setText("thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jButton3.setText("sửa ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbonam);
        rbonam.setText("nam");

        buttonGroup1.add(rbonu);
        rbonu.setText("nữ");

        combomid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combomidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnthem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(combomid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(rbonam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbonu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnreset))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnthem)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combomid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbonam)
                            .addComponent(rbonu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combomidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combomidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combomidActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnresetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update STUDENT set HOTEN=? , IDCLASS=? ,gioitinh = ? where MaSV =? ";
            pred = cn.prepareStatement(sql);
            pred.setString(1, txthoten.getText());
            pred.setString(2, combomid.getSelectedItem() + "");
            pred.setString(4, txtmasv.getText());
            String gt = rbonam.isSelected() ? "nam" : "nữ";
            if (gt.equals("nam")) {
                rbonam.setSelected(true);
            } else {
                rbonu.setSelected(true);
            }
            pred.setString(3, gt);
            pred.executeUpdate();
            mess("đã sửa");
            pred.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        check_dl();
        check_khoa();
        try {
            String sql = "insert STUDENT values(?,?,?) ";
            pred = cn.prepareStatement(sql);
            pred.setString(2, txthoten.getText());
            pred.setString(3, combomid.getSelectedItem() + "");
            pred.setString(1, txtmasv.getText());
            pred.executeUpdate();
            mess("đã thêm vào csdl");
            clear();
            pred.close();
        } catch (Exception e) {
            e.printStackTrace();
            mess("trùng khóa");
        }
    }//GEN-LAST:event_btnthemActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FORM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FORM2().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnthem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combomid;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbonam;
    private javax.swing.JRadioButton rbonu;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmasv;
    // End of variables declaration//GEN-END:variables
}
